---

- hosts: localhost
  gather_facts: no
# get IP of new server 
  vars_prompt:
  - name: new_host
    prompt: New host IP address
    private: no
  - name: new_host_name
    prompt: New host Name
    private: no
  vars_files:
     - /home/ansible/vault/credentials-01.yml

  tasks:
  - name: Add host to inventory file
    lineinfile:
      path: /home/ansible/inventory
      state: present
      line: "{{ new_host_name }} ansible_host={{ new_host }}"

  - name: Add provided host to temporary inventory
    add_host:
      name: "{{ new_host }}"
      groups: temporary_host_group 
      ansible_user: "{{ server_user }}"
      ansible_password: "{{ server_password }}"
  - name: Add provided host to known hosts
    shell: ssh-keyscan -H "{{ new_host }}" >> ~/.ssh/known_hosts
    tags: 
      - knownhosts

- hosts: temporary_host_group
  vars_files:
    - /home/ansible/vault/credentials-01.yml
  vars:
    ansible_become_password: "{{ server_password }}"
  become: true
  tasks:
  - name: Create ansible user
    ansible.builtin.user:
      name: ansible
      home: /home/ansible
      shell: /bin/bash
      password_lock: true

  - name: create ssh directory for ansible user
    ansible.builtin.file:
      path: /home/ansible/.ssh
      state: directory
      mode: 0700
      owner: ansible
      group: ansible

  - name: create ssh directory for admin user
    ansible.builtin.file:
      path: "/home/{{ server_user}}/.ssh"
      state: directory
      mode: 0700
      owner: "{{ server_user }}"
      group: "{{ server_user }}"

  - name: copy ssh public key for ansible user
    template:
      src: /home/ansible/ansiblekey.j2
      dest: /home/ansible/.ssh/authorized_keys
      owner: ansible
      group: ansible
      mode: 0600

  - name: copy ssh public key for admin user
    template:
      src: /home/ansible/adminkey.j2
      dest: "/home/{{server_user}}/.ssh/authorized_keys"
      owner: "{{ server_user }}"
      group: "{{ server_user }}"
      mode: 0600

  - name: copy sudoers file for ansible user
    copy:
      src: /home/ansible/ansible-sudo
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: 0600

  - name: add config template to /etc/sshd/ssh_config.d/
    template:
      src: /home/ansible/ansible1/00_sshd_basic.j2
      dest: /etc/ssh/sshd_config.d/00_sshd_basic.conf
      owner: root
      group: root
      mode: 0600
    
  - name: install fail2ban
    dnf:
      name: fail2ban
      state: latest

  - name: remove cockpit
    dnf:
      name: cockpit
      state: absent
  
  - name: restart sshd service
    systemd_service:
      state: restarted
      name: sshd
